baseURL: 'https://www.tedxhartwoodelementary.com/'
languageCode: 'en-us'
title: 'TEDxKids@HartwoodElementary'
disableKinds:
- RSS
menu:
    main:
        - identifier: events
          name: Events
          weight: -100
          url: /events/
taxonomies:
    event: events
