baseURL: "https://www.tedxhartwoodelementary.com/"
languageCode: "en-us"
title: "TEDxKids@HartwoodElementary"
googleAnalytics: G-9CG7Y41PSS
disableKinds:
  - RSS
menu:
  main:
    - identifier: events
      name: Events
      weight: -100
      url: /events/
taxonomies:
  event: events
markup:
  goldmark:
    renderer:
      unsafe: true
